# Generated by Django 4.1.3 on 2022-11-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=240, verbose_name='team name')),
                ('team_description', models.TextField()),
                ('captains', models.ManyToManyField(related_name='team_captains', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('team_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
